// Shared plans data
window.PLANS = [
  { id: 1, title: {he:'מגדל למידה מונטסורי', en:'Montessori Learning Tower'}, desc: {he:'פתרון עיצובי ופונקציונלי שמאפשר לילדים לעמוד בגובה משטחי עבודה של מבוגרים בבטחה ובעצמאות, ומעודד אותם לקחת חלק פעיל במטלות יומיומיות.', en:'A functional design that lets children safely and independently reach adult countertop height and take an active part in daily tasks.'}, price: 20, currency: '₪', img: 'pics/learnningtower.jpg', img2: '', tags: ['kids','montessori','learning','tower'] },
  { id: 2, title: {he:'אדנית עץ ריבועית', en:'Square Wooden Planter'}, desc: {he:'אדנית לגינה מעץ, מושלמת לגידול פרחים, צמחי תבלין וירקות, משדרגת כל פינת ישיבה.', en:'A wooden garden planter, perfect for growing flowers, herbs and vegetables; elevates any seating area.'}, price: 15, currency: '₪', img: 'pics/gardenbed.jpg', img2: '', tags: ['planter','garden','wood'] },
  { id: 3, title: {he:'מיטת מעבר מונטסורית', en:'Montessori Toddler Bed'}, desc: {he:'מיטת מעבר מונטסורית לילד שלכם: תוכנית בנייה קלה, מפורטת ונגישה, הכוללת את כל השלבים, רשימת החומרים וכלי העבודה כדי שתוכלו לבנות במו ידיכם מיטה בטוחה שתעודד עצמאות, חופש תנועה וביטחון עצמי.', en:'A Montessori toddler transition bed: a clear, easy-to-follow building plan with all steps, materials and tools, so you can build a safe bed that fosters independence, freedom of movement and confidence.'}, price: 25, currency: '₪', img: 'pics/montesorribed.jpg', img2: '', tags: ['bed','kids','montessori'] },
  { id: 4, title: {he:'קמפוס בורד לאימונים', en:'Campus Board for Training'}, desc: {he:'לוח אימונים מודולרי, שיאפשר לכם לשפר את טכניקת הטיפוס והכוח בכל רגע, בנוחות הבית', en:'A modular training board to improve climbing technique and strength anytime, from the comfort of your home.'}, price: 15, currency: '₪', img: 'pics/campusboard.jpg', img2: '', tags: ['climbing','training','fitness'] },
  { id: 5, title: {he:'נדנדה זוגית', en:'Double Swing'}, desc: {he:'הגשימו את חלום הילדות: תוכנית בנייה מפורטת לנדנדה זוגית שתעניק לכם רגעים קסומים של שלווה וכיף, לחצר או למרפסת.', en:'Make the childhood dream come true: a detailed plan for a double swing that brings magical, peaceful moments to your yard or balcony.'}, price: 25, currency: '₪', img: 'pics/swing.jpg', img2: '', tags: ['swing','outdoor','garden'] },
  { id: 6, title: {he:'מתלה מעילים', en:'Coat Rack'}, desc: {he:'סדר ויעילות בכניסה לבית: תוכנית פשוטה לבניית מתלה מעילים מעץ שמשלב פונקציונליות ועיצוב, ומוסיף טאץ\' אישי לכל כניסה.', en:'Order and efficiency at your entryway: a simple plan for a wooden coat rack that blends function and design and adds a personal touch to any entrance.'}, price: 12, currency: '₪', img: 'pics/coatstand.jpg', img2: '', tags: ['coat','hallway','storage'] },
  { id: 7, title: {he:'שולחן עבודה', en:'Workbench'}, desc: {he:'צרו סביבה שמעוררת השראה: תוכנית בנייה מודולרית לשולחן עבודה מעץ, שמתאימה לכל צורך ומסייעת לשפר פרודוקטיביות וריכוז.', en:'Create an inspiring workspace: a modular wooden workbench plan adaptable to your needs, helping boost productivity and focus.'}, price: 30, currency: '₪', img: 'pics/tablework.jpg', img2: '', tags: ['workbench','shop','desk'] },
  { id: 8, title: {he:'ספרייה', en:'Bookcase'}, desc: {he:'פתרון אחסון מעוצב לספרים ולפריטים אישיים: תוכנית בנייה גמישה לספרייה מעץ, שתתאים בדיוק למידות ולסגנון של הבית שלכם.', en:'A stylish storage solution for books and personal items: a flexible wooden bookcase plan you can tailor to your home\'s measurements and style.'}, price: 22, currency: '₪', img: 'pics/libary.jpg', img2: '', tags: ['bookcase','storage','living'] },
];
